name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          name: Build-artifacts
          path: build/

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: Build-artifacts
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          artifact_name: Build-artifacts

  scrape:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Algolia Crawler creation and crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.13
        id: algolia_crawler
        with:
          crawler-user-id: ${{ secrets.DOCS_ALGOLIA_CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.DOCS_ALGOLIA_CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.DOCS_ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.DOCS_ALGOLIA_API_KEY }}
          site-url: 'https://cacic.dev.br'
          crawler-name: 'CACiC Homepage'